[[plugins]]
	repo= 'scrooloose/nerdtree'
	hook_add='''
		autocmd StdinReadPre * let s:std_in=1
		autocmd vimenter * if argc() == 0 && !exists("s:std_in") |NERDTree|endif
	'''

[[plugins]]
	repo = 'Xuyuanp/nerdtree-git-plugin'
	depends = 'scrooloose/nerdtree'

[[plugins]]
	repo = 'haya14busa/vim-easymotion'
	#repo = 'Lokaltog/vim-easymotion'
	hook_add='''
		map <Leader> <Plug>(easymotion-prefix)
		let g:EasyMotion_do_mapping = 0
		nmap s <Plug>(easymotion-s2)
		nmap S <Plug>(easymotion-S)

	'''
