
[[plugins]]
	repo = 'Shougo/dein.vim'

[[plugins]]
	repo = 'cespare/vim-toml'
[[plugins]]
	repo = 'Shougo/vimproc.vim'
	hook_post_update = '''
		let cmd = 'make'
		let g:dein#plugin.build = cmd'
	'''

# [[plugins]]
# 	repo = 'thinca/vim-quickrun'
# 	hook_post_update = '''
# 	let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
# 	'''
#

[[plugins]]
	repo = 'Shougo/deoplete.nvim'
	hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
	repo = 'tomtom/tcomment_vim'

#[[plugin]]
#	repo = 'Townk/vim-autoclose'

[[plugins]]
	repo ='vim-airline/vim-airline-themes'
[[plugins]]
	repo ='vim-airline/vim-airline'
	hook_add='''
		let g:airline_powerline_fonts = 1
		let g:airline_theme = 'badwolf'
		let g:airline#extensions#tabline#enabled = 1
		let g:airline#extensions#virtualenv#enabled = 1

		let g:airline#extensions#hunks#enabled = 0
		let g:airline#extensions#ale#enabled = 1
		let g:airline#extensions#ale#error_symbol = 'E:'
		let g:airline#extensions#ale#warning_symbol = 'W:'
		set laststatus=2
	'''
		


[[plugins]]
	repo ='tpope/vim-fugitive'

[[plugins]]
	repo ='airblade/vim-gitgutter'


[[plugins]]
	repo = 'cohama/lexima.vim'
	

[[plugins]]
	# repo = 'haya14busa/vim-easymotion'
	repo = 'Lokaltog/vim-easymotion'
	hook_add='''
		let g:EasyMotion_do_mapping = 0
		map <Leader> <Plug>(easymotion-prefix)
		nmap s <Plug>(easymotion-s2)
		xmap s <Plug>(easymotion-s2)
		nmap S <Plug>(easymotion-S)
		nmap <Leader>L <Plug>(easymotion-overwin-line)

	'''
