
[[plugins]]
	repo = 'osyo-manga/vim-precious'
	depends =['Shougo/context_filetype.vim']

[[plugins]]
	repo = 'Shougo/context_filetype.vim'
	hook_add='''
	if !exists('g:context_filetype#filetypes')
	let g:context_filetype#filetypes={}
	endif
	'''
