[[plugins]]
	repo= 'scrooloose/nerdtree'
	hook_add='''
		autocmd StdinReadPre * let s:std_in=1
		autocmd vimenter * if argc() == 0 && !exists("s:std_in") |NERDTree|endif
	'''

[[plugins]]
	repo = 'Xuyuanp/nerdtree-git-plugin'
	depends = 'scrooloose/nerdtree'


# [[plugins]]
# 	repo = 'haya14busa/vim-easymotion'
# 	#repo = 'Lokaltog/vim-easymotion'
# 	hook_post_source='''
# 		map <Leader> <Plug>(easymotion-prefix)
# 		let g:EasyMotion_do_mapping = 0
# 		nmap s <Plug>(easymotion-s2)
# 		nmap S <Plug>(easymotion-S)
#
# 	'''
#

[[plugins]]
	repo = 'thinca/vim-quickrun'
	# hook_post_update

	hook_post_source = '''
	let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
	let g:quickrun_config = get(g:, 'quickrun_config', {})
	let g:quickrun_config._ = {
      \ 'runner'    : 'vimproc',
      \ 'runner/vimproc/updatetime' : 60,
      \ 'outputter' : 'error',
      \ 'outputter/error/success' : 'buffer',
      \ 'outputter/error/error'   : 'quickfix',
      \ 'outputter/buffer/split'  : ':rightbelow 8sp',
      \ 'outputter/buffer/close_on_empty' : 1,
      \ }



	'''
	on_cmd = ['QuickRun']


[[plugins]]
	repo= 'scrooloose/syntastic'

	hook_add='''
		let g:syntastic_enable_signs=1
		let g:syntastic_auto_loc_list=2
		let g:syntastic_mode_map = {'mode': 'passive',\ 'active_filetypes': ['python','java']} 
		augroup AutoSyntastic
			autocmd!
			autocmd InsertLeave,TextChanged * call s:syntastic() 
		augroup END
		function! s:syntastic()
			w
			SyntasticCheck
		endfunction
	'''
	on_ft = ['python']
